<?php

namespace BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{
    public function findByUser(User $user, $nowTime) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT a FROM BoardBundle:Ad a WHERE a.owner = :user AND a.expirationDate > :nowTime ORDER BY a.creationDate DESC'
        );
        $query->setParameter('user', $user);
        $query->setParameter('nowTime', $nowTime);

        return $query->getResult();
    }
}
