<?php

namespace BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findCategoriesOrderByName() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT c FROM BoardBundle:Category c ORDER BY c.name ASC'
        );

        return $query->getResult();
    }

    public function findAdsinCategoryOBCreationDate(Category $category, $dateNow) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT a FROM BoardBundle:Ad a JOIN a.categories t WHERE t = :category AND a.expirationDate > :dateNow ORDER BY a.creationDate DESC'
        )->setParameter('category', $category)->setParameter('dateNow', $dateNow);

        return $query->getResult();
    }

    public function findAdsinCategoryOBExpirationDate(Category $category, $dateNow) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT a FROM BoardBundle:Ad a JOIN a.categories t WHERE t = :category AND a.expirationDate > :dateNow ORDER BY a.expirationDate ASC'
        )->setParameter('category', $category)->setParameter('dateNow', $dateNow);

        return $query->getResult();
    }



}
